### PR TITLE
Fixes #12. Log promise errors to the console. Otherwise they are silent

### LINKED ISSUE #12: Log when the import rejects
https://github.com/canjs/can-view-import/blob/7f13cc4ad8e802c8fdee7850c4dcfcd235033fe9/can-view-import.js#L20

Currently we do not log when the error rejects. It's normal to have code like:

```html
<can-import from="somewhere">
       {{#if isPending}}
          <div class="loader">Loading...</div>
        {{else}}
          <foo-bar/>
        {{/if}}
</can-import>
```

That does not handle the error case.

### PR DESCRIPTION
**Pull request by mjstahl**

### CODE REVIEW

**Comment by matthewp** [comment]
I think you want to use https://github.com/canjs/can-util/blob/master/js/dev/dev.js  for this, some browsers (IE) don't support console.error.

@phillipskevin is it safe to use `dev.warn()` here? We **do** want these errors to show up in production.

**Comment by phillipskevin** [comment]
`dev.warn` is a no-op in production, but you can use `console.warn` directly. A few places are doing that for warnings that should show up in production.

**Comment by matthewp** [comment]
Do we need to use check if `console` exists for old IE compat @phillipskevin ?

**Comment by phillipskevin** [comment]
I don't think we do. I don't think IE9 throws errors for calling `console.log` when the devtools are closed anymore (from googling, it looks like maybe it stopped doing this after Windows XP).

However, @daffl did add these checks for IE9 in https://github.com/canjs/canjs/commit/004d956e4eddeddfb9ac949dc99d34fe211caaa7. Maybe this is just because these are loaded in iframes? @daffl should we be checking if `console.log` exists other places we're using it?

**Comment by matthewp** [comment]
Going to use https://github.com/canjs/can-util/pull/171 once that lands.

**Pull request merged**
